apiVersion: v2
name: mealie-k3s
description: A Helm chart for deploying Mealie with Postgres and MetalLB on k8s.
type: application
version: 0.1.0
appVersion: "1.0.0" # Or the specific Mealie version you are targeting

dependencies:
- name: postgresql
  version: "14.x.x" # Use a specific, stable version
  repository: "https://charts.bitnami.com/bitnami"
  alias: postgresql # We will refer to this as 'postgresql' in values.yaml
  condition: postgresql.enabled

- name: metallb
  version: "0.14.x" # Use a specific, stable version
  repository: "https://metallb.github.io/metallb"
  alias: metallb
  condition: metallb.enabled