apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mealie-svc
spec:
  type: {{ .Values.mealie.service.type }}
  ports:
  - port: {{ .Values.mealie.service.port }}
    targetPort: 9000
    protocol: TCP
  selector:
    app: mealie